<?php include_once '../includes/header.php' ?>
<?php include_once '../sections/main.php' ?>
<?php include_once '../sections/projects.php' ?>
<?php include_once '../sections/about.php' ?>
<?php include_once '../sections/cooperation.php' ?>
<?php include_once '../sections/team.php' ?>
<?php include_once '../sections/order.php' ?>
<?php include_once '../sections/contact.php' ?>
<?php include_once '../includes/footer.php' ?>